### ISSUE TITLE
Support for regex 

### ISSUE THREAD

**Issue by bonanza123** [rsharo/bgrep#2]
Besides wildcard regex support would be great (e.g. in perl style)

**Comment by rsharo** [comment]
Unfortunately regular expressions can quickly become pathological when searching in binaries, since there is no "beginning of line" or "end of line".  This is why the program exists at all:  to find sequences that are hard to match when running the real `grep` on a binary.

To search for regular expressions, I'd recommend using `grep` or writing an actual `perl` script.  To `grep` for a sequence that includes null characters, you can use the following "trick" to match against the hexdump. Just be aware that arbitrary-length patterns like `\w+` will not go well in a binary.

`xxd -p [file] | tr -d '\n' | grep -oP [pattern] | xxd -p -r`
